### ISSUE TITLE
Sharing config.json sample

### ISSUE THREAD

**Issue by coderbag** [IntuitDeveloper/SampleApp-WebhookNotifications-nodejs#2]
There are
- authorization_endpoint
- scopes / connect_to_quickbooks
- token_endpoint 

in the source code. But they were not mentioned in README

I'd like to see the sample config.json

**Comment by anilkumarbp** [comment]
Thanks for pointing out.

Added changes to the `README` [here](https://github.com/IntuitDeveloper/SampleApp-WebhookNotifications-nodejs#configuration)

You can refer to the sample-config.json [here](https://github.com/IntuitDeveloper/SampleApp-WebhookNotifications-nodejs/blob/master/sample-config.json)
